version: '3.8'

services:
  beehive-backend-prod:
    container_name: beehive-backend-prod
    build: 
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - 8080:80
 