version: '3.8'

services:
  beehive-backend-dev:
    image: beehive-backend-dev
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: node-beehive-backend-dev
    command: yarn run dev -L
    env_file:
      - .env
    volumes:
      - ./:/usr/share/nginx/html
      - ./node_modules:/node_modules/ 
    ports:
      - "4000:4000"