name: 🐳 Build and Push Docker Image

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: The tag to push to the Docker registry.

jobs:
  build:
    name: 🐳 Build
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🧑‍💻 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Setup cache
      - name: ⚡️ Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 🐳 Build Production Image from Docker Compose
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker compose -f docker-compose.dev.yml build 
          docker tag beehive-backend-dev bafode/beehive-backend-dev:latest
          docker push bafode/beehive-backend-dev:latest
        env:
          DOCKER_BUILDKIT: 1

      # Manage cache
      - name: 🚚 Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
